apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocr-model-server-sa
  namespace: ocr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocr-model-server-role
  namespace: ocr
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocr-model-server-rb
  namespace: ocr
subjects:
  - kind: ServiceAccount
    name: ocr-model-server-sa
roleRef:
  kind: Role
  name: ocr-model-server-role
  apiGroup: rbac.authorization.k8s.io