apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-api-gateway
  namespace: ocr
  labels:
    app: api-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: ocr-api-gateway-sa
      containers:
        - name: api-gateway
          envFrom:
            - configMapRef:
                name: app-config        
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: ocr-api-gateway-svc
  namespace: ocr
spec:
  type: {{ .Values.service.type }}
  selector:
    app: api-gateway
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001