apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocr-api-gateway-sa
  namespace: ocr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocr-api-gateway-role
  namespace: ocr
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocr-api-gateway-rb
  namespace: ocr
subjects:
- kind: ServiceAccount
  name: ocr-api-gateway-sa
roleRef:
  kind: Role
  name: ocr-api-gateway-role
  apiGroup: rbac.authorization.k8s.io