apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ocr-project
  namespace: argocd
spec:
  description: OCR Microservices Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: ocr
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'