apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocr-api-gateway
  namespace: argocd
spec:
  project: ocr-project
  source:
    repoURL: http://host.minikube.internal:8082
    chart: api-gateway
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: ocr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true