apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocr-model-server
  namespace: argocd
spec:
  project: ocr-project
  source:
    repoURL: http://host.minikube.internal:8082
    chart: model-server
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: ocr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true