replicaCount: 1

image:
  repository: piyasith/ocr-api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

configmap:
  kserveUrl: "http://model-server:8080/v2/models/ocr-model/infer"